# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ABFRealmTableViewControllerExample' do
  pod 'Realm'
  pod 'RBQFetchedResultsController'
  pod 'Colours'
end

target 'ABFRealmTableViewControllerExampleTests' do
  pod 'Realm/Headers'
end

